server:
  port: 9091

spring:
  application:
    name: demo-debug
  cassandra:
    contact-points: localhost
    port: 9042
    keyspace-name: student_db
    local-datacenter: datacenter1
    schema-action: create_if_not_exists